### ISSUE TITLE
Multiple sounds in masked format

### ISSUE THREAD

**Issue by writen-unclear** [dnsev/4cs#1]
Currently when the userscript loads a masked multi-sound file such as

http://archive.foolz.us/a/thread/77601296/#77603712

it misses the magic numbers of all but the first Ogg file and therefore only sees one sound.

The problem appears to be the line

i += magic_strings_ui8[s].length;

which skips magic_strings_ui8[s].length bytes without properly updating the mask state.  Commenting out the line causes all sounds to be loaded.

**Comment by dnsev** [comment]
Will be fixed in 1.1
