### ISSUE TITLE
Youtube embedding fails to work with adblock plus

### ISSUE THREAD

**Issue by zawa3zawa** [dnsev/4cs#11]
Using AdblockPlus with the greasemonkey extension stops the embed from working.
I haven't explored options to exclude it from the filter, but if anyone runs into issues with the embed, take a look at adblock.

**Comment by vampiricwulf** [comment]
Are you sure you're not using custom CSS that `display: none !important;` on `iframe`?

**Comment by dnsev** [comment]
The only URLs the extension uses for Youtube are:
`"//gdata.youtube.com/feeds/api/videos/" + vid_id;`
and
`"http://www.youtube.com/v/" + vid_id + "?version=3"`
and
`"//www.youtube.com/iframe_api"`

Other than that, check what vampiricwulf suggested, and make sure you aren't blocking iframes
