### ISSUE TITLE
Media Player and 4chanX QR no longer co-existing peacefully

### ISSUE THREAD

**Issue by manoftron** [dnsev/4cs#18]
It seems that with moots pushing 4chan x to Greasemonkey, the media player and uploading gets fucked over. Probably intentional. Just letting you guys know about this if you don't already.

**Comment by jdsch** [comment]
4chan X upgraded to v3 which includes a lot of new features, which removed the #spoilerLabel label
https://4chan-x.just-believe.in/
In the meantime, just use v2

**Comment by dnsev** [comment]
Yeah, I assumed this would happen. I'll look into it and see what needs changing.

**Comment by dnsev** [comment]
Updated in [4.4.4](https://github.com/dnsev/4cs/commit/48f64ef8295af40df58e1beda6938e83eb63731c)

As a side note, the uploader loses a bit of functionality with 4chan-x 3: it can't auto-detect sounds from files by using the normal file selection box; you have to manually use the sounds checkbox.
