### ISSUE TITLE
moot blocked some sounds!

### ISSUE THREAD

**Issue by Lyrica-Prismriver** [dnsev/4cs#19]
Apparently moot made some changes to the embedded archive filter, of four sounds i've tried, only two could be uploaded, the rest get embedded image errors.

Any way you can update the mask dnsev?

**Comment by jdsch** [comment]
Moot hasn't implemented a method of detecting embedded sounds yet. He's implemented an algorithm that calculates the image dimensions (how wide and high it is) and sets a file size limit on that. That way, you can never upload a 1x1 image that is 3MB.
All what you need to do is increase the JPG/PNG file size dimensions which only increases the file size a little bit. At least to 700x700 for a 3MB file if I'm correct. I don't know the exact calculations.

**Comment by Lyrica-Prismriver** [comment]
Yeah I know, I just found that out in the IRC a few minutes ago.

dnsev, can you make a work around that can do upscale images or something like that?

**Comment by dnsev** [comment]
Added an upscaling application that upscales and converts files to the proper format when necessary.
[Link](http://dnsev.github.io/4cs/#bigger)

By default it upscales to at least 800x800 pixels.
