### ISSUE TITLE
4chanx V3 is now official

### ISSUE THREAD

**Issue by vampiricwulf** [dnsev/4cs#20]
Time to upgrade!
Not really though, just need to move the settings/menu link to somewhere accessible. (On main board pages)

**Comment by jdsch** [comment]
The media player menu link is at the top and bottom of each thread, although isn't available on the main board page

**Comment by vampiricwulf** [comment]
Still needs to be fixed for main board page. (as you said)

**Comment by dnsev** [comment]
Updated in [4.5](https://github.com/dnsev/4cs/commit/d26b32cf49936cde6b1b697cbd32168e17d47118)/[cl](http://dnsev.github.io/4cs/#changes?highlight=4_5&scroll=4_5)

**Comment by nstepien** [comment]
You may want to use this:
https://github.com/MayhemYDG/4chan-x/wiki/Menu-API

**Comment by dnsev** [comment]
Updated in [4.5.1](https://github.com/dnsev/4cs/commit/4b75b5ec63c1885fcd1170fcb11a3613ba26e290)/[cl](http://dnsev.github.io/4cs/#changes?highlight=4_5_1&scroll=4_5_1)
