### ISSUE TITLE
4chan X recent changes

### ISSUE THREAD

**Issue by Matrius** [dnsev/4cs#23]
I'm assuming [this](https://github.com/MayhemYDG/4chan-x/commit/e0233198dd262b26d71ccef940bdb99682ae4c41) change messed up sound uploading with the sounds form open

Upload Error
An error occured while attempting to submit your post.
This may happen due to script incompatability. If you want to use this feature, submit an issue request, or disable this feature and install a different upload script.
You can try to submit your post by closing the sounds panel.
Errors
Submit form key "name" could not be found.
Submit form key "email" could not be found.
Submit form key "sub" could not be found.

**Comment by dnsev** [comment]
Updated in [4.5.4](https://github.com/dnsev/4cs/commit/cd2f41964fdd24363a2d3718ebd3359cdc070dd7)/[cl](http://dnsev.github.io/4cs/#changes?highlight=4_5_4&scroll=4_5_4).
