### ISSUE TITLE
CSS annoyance

### ISSUE THREAD

**Issue by vampiricwulf** [dnsev/4cs#24]
```
.MPMenu.MPMenuClosed.MPHighlightShadow2px.reply.post
```

Do you really need the `.reply.post`?

**Comment by dnsev** [comment]
What `.reply.post` does is applies the default background color of a post to whatever that's tacked onto. It's so I don't have to manually detect what the color is on my side, it just uses pre-existing CSS rules. `.reply` is required because some userscripts make the first reply have a transparent background.

**Comment by vampiricwulf** [comment]
I see, that's annoying. Oneechan (When fit-width is active) has  `.reply.post` as `display:block` so that window is forever expanded. Maybe I can discuss with @seaweedchan to apply it to `#delform .reply.post`  without it disrupting anything else.

**Comment by dnsev** [comment]
I could force them to display:inline-block on my end easily too.

**Comment by vampiricwulf** [comment]
If they're both `!important` who'd win?

**Comment by dnsev** [comment]
If I give mine more rules, mine should. I'll test it out and see anyway.

**Comment by vampiricwulf** [comment]
Is that so? Thank you.

**Comment by dnsev** [comment]
Might be fixed in [4.6.4](https://github.com/dnsev/4cs/commit/7eb386c3321974efe48699200b1f92bd862a50a5); see how it does.

**Comment by vampiricwulf** [comment]
That worked!
Thank you~

**Comment by vampiricwulf** [comment]
> Reopened
> Closed

Did it for the feel of accomplishment?

**Comment by dnsev** [comment]
To see if I could. I was tempted to do it more.

**Comment by seaweedchan** [comment]
Huh. I was not aware anyone used both. How well does that work?

**Comment by vampiricwulf** [comment]
> How well does that work?

Who is this directed at?
