### ISSUE TITLE
Disable 4cs on /f/

### ISSUE THREAD

**Issue by vampiricwulf** [dnsev/4cs#25]
Is it really necessary there? Images can't be uploaded there.

**Comment by dnsev** [comment]
Not so much a question of "is it necessary" as "it's just not disabled anywhere." I'll see what I can do.

**Comment by dnsev** [comment]
Updated in [4.6.5](https://github.com/dnsev/4cs/commit/15300c887b76d55fd56d6df9961794d7dbd05516)
