### ISSUE TITLE
Add order value to menu entry

### ISSUE THREAD

**Issue by seaweedchan** [dnsev/4cs#26]
To keep it close to the other submenus when there are scripts like OneeChan, 4chan X Name Sync, and ExLinks that add links to the bottom of the header menu.

Somewhere between 105 and 111 (higher value placing it lower) OneeChan has an order value of 120, and the other two have values of 112.

**Comment by dnsev** [comment]
Changed in [4.6.6](https://github.com/dnsev/4cs/commit/16270d830bd8fc67c3b6462c72821080b200fdde). I still find it odd that custom entries aren't by default at the bottom, but whatever.
