### ISSUE TITLE
issues with 4chan

### ISSUE THREAD

**Issue by lakdaisy** [dnsev/4cs#32]
After following the guide here http://dnsev.github.io/4cs/#guide?tips&video
At step 7 I encountered problems when I tried to upload image-embed.jpg, which I was promptly interrupted with a message informing that the image file has a embedded file. Therefore preventing me from using it.

This happened in /v/ board

**Comment by vampiricwulf** [comment]
There's a really basic block that 4chan does that if your image's dimensions are too small for the file size, it is automatically blocked. The ways around this are to use dnsev's "bigger" program to resize the image while embedding, or to embed using a .gif file.

**Comment by dnsev** [comment]
What @vampiricwulf said; use [bigger](http://dnsev.github.io/4cs/#bigger) and it should work.

**Comment by lakdaisy** [comment]
That worked, thank you.
May the socialist dream and communist utopia come true through you actions.
