### ISSUE TITLE
Very slow to put sounds into Media Player list 

### ISSUE THREAD

**Issue by ghost** [dnsev/4cs#33]
I am going to assume it is related to the Firefox update (23.0) that was released recently as that is when I began to notice the issue, but other users have not had the issue. Basically, when I load an embedded sound, it loads fairly quickly. However, it takes about 15+ seconds to be put into the media player list and begin playing the actual sound. When it is loading into the media player list, it makes my browser so laggy so when I type text, it takes a few seconds to appear and scrolling is also delayed.

Tried reinstalling Greasemonkey and Media Player but still get the issue. Videos load fine in the media player and play with no delay, only sound in images. I disabled my other scripts in Greasemonkey but that did not help.

**Comment by dnsev** [comment]
Is Firefox 23.0 even out? Mine stays on 22.0 even when I open the page that updates it.

Anyway, using Firefox 22.0 to load a sound/video is noticeably faster than Nightly 25.whatever for the same file, so I'll have to see what lags it like crazy.

**Comment by dnsev** [comment]
So basically what I've found out is that whatever version of Javascript Nightly 25 is using is worse than whatever Firefox 22 is using; case in point:

``` javascript
var len = 1686518;
for (var i = 0; i < len; ++i) x += 1;
```

On Nightly, takes <b>231ms</b>
On Firefox, takes <b>6ms</b>

I don't know if this is what's being used on your Firefox 23(?) version, but if it is, then I have no way of fully eliminating the problem. The best I could hope to do is reduce the load times from say 16 seconds to 8 seconds, and that's being optimistic.

Also not sure where exactly I'd look to find out about the differences in Javascript between versions of Firefox to figure out why it's so damn slow.

**Comment by ghost** [comment]
Yeah it was the first beta for 23.0. I just went back to 22 and this time opted out of automatic updates. Hopefully that should solve it and when 23.0 releases for everyone, no one has the issue. Now to just wait for a sound thread. Thanks.

**Comment by ghost** [comment]
Used my own sound to see if it worked, and it did. Guess it is a javascript issue with the new update.
