### ISSUE TITLE
Can you add support for 38chan?

### ISSUE THREAD

**Issue by mootisafag** [dnsev/4cs#34]
Do you think you could add in support for 38chan? Right now, the script works if you have a hotkey bound for opening  the player and included boards.38chan.net/\* in the script; you just have to drag images in the player itself. 

I was wondering if you could make a minor adjustment to the script so we could see the media player script button on 38chan and have [tags] working

**Comment by dnsev** [comment]
[Should be working now](https://github.com/dnsev/4cs/commit/c67378114a515bc5ac7f4e1bd7bc821fa4a5753b), tags should be working properly too.

**Comment by mootisafag** [comment]
Thanks based dnsev

**Comment by dnsev** [comment]
Update again to [4.7.0.1](https://github.com/dnsev/4cs/commit/99f4d16ad6be3613f8a801be2c1bfc03be25a220) to fix the bug you may or may not have seen on the test file I used.

Should be good to go now.
