### ISSUE TITLE
Sound player not working

### ISSUE THREAD

**Issue by P2K9** [dnsev/4cs#37]
When I go to load a sound by clicking on the sounds button, rather than loading the sound (sounds does change to loading... but nothing ever actually loads) it just takes me to the top of the page. I am also unable to open the Media Player by going to Media Player->Open Player but I can open the Settings page. I'm using Scriptish 0.1.8 with 4chan Media Player 4.7.0.2 on Firefox 22. 

If more details are needed let me know.

**Comment by dnsev** [comment]
Sounds like an error is happening.

Check the error console when this happens (ctrl+shift+K) and you should get something like this:
![web_console](https://f.cloud.github.com/assets/3087287/120665/f5ae19a6-6d1d-11e2-908c-3a20c28bdb48.png)

Look for errors colored in orange, particularly ones sourced from "4cs.user.js" on the right.

If you have any other userscripts installed that may be affecting it, also name those.

**Comment by P2K9** [comment]
This is what my error console looks like 

![sperror](https://f.cloud.github.com/assets/5187061/945152/44ccf528-02f8-11e3-8859-b30ce0fb7eaf.png)

I have no other scripts, but I have the HTTPS-Everywhere and Ghostery extensions

**Comment by dnsev** [comment]
Does the error console screencap come after you've clicked a sounds link and it takes you to the top of the page? You can also disable the "Net" messages, as only the orange ones are important.

If you still find no errors, try updating Scriptish. And if that fails, use Greasemonkey.

I tried under Scriptish 0.1.11 and it ran, and it normally runs under Greasemonkey anyway.

**Comment by P2K9** [comment]
Updated to the latest Scriptish and it works now, although now there is a big delay (6-8 seconds) between click on the sound link and it being added to the player, but I realize from one of the other issue reports that this is a problem with FF itself and not the player.

**Comment by dnsev** [comment]
You can thank Firefox 23 for that.
