### ISSUE TITLE
Conflict with Oneechan style script.

### ISSUE THREAD

**Issue by FrostyDynamic** [dnsev/4cs#38]
Whenever I have Oneechan enabled, a few things get in the way. One would be that whenever I use Hover preview for videos, it doesn't go away, and the second would be that the [media player] button at the top of the screen covers the filename for OP's image.

**Comment by dnsev** [comment]
The filename issue should be fixed with 4.7.0.3, but I can't re-create the hover preview problem you have. Do you have embedding enabled in your 4chanx?

**Comment by FrostyDynamic** [comment]
No, I have none of the linktify options enabled. The problem only happens when I have Oneechan enabled, and not when I just have 4chan x enabled.

**Comment by dnsev** [comment]
Alright, I found the problem. Seemed to be a CSS priority issue. It should be fixed in [4.7.1](https://github.com/dnsev/4cs/commit/4a1a7a27ec0ff026e6e1b8a7c828e06cedd03e16) now.
