### ISSUE TITLE
Re-encoding errors (and some feature requests)

### ISSUE THREAD

**Issue by Yoposoc** [dnsev/4cs#4]
Ok, I just got done with converting all .jpg and .png files. Took about a day.

-Some .png files came out completely corrupted. The majority of them (not sure if all) seems to be .jpg files that were converted into .png by the program. 
Original: 
[choo choo TETSUMUSU ](https://f.cloud.github.com/assets/2718371/77144/412fb17e-611a-11e2-9001-b6de9109f41d.jpg)
Encoded: 
[choo choo TETSUMUSU -embed](https://f.cloud.github.com/assets/2718371/77099/6fe10ecc-6116-11e2-8d02-5b1ccae4a917.png)

-Some of them came out slightly corrupted, like these:
[Cirino](https://f.cloud.github.com/assets/2718371/77108/2335edc6-6117-11e2-955f-4d982d1a6b03.jpg)
[Cirino-embed](https://f.cloud.github.com/assets/2718371/77109/2374350e-6117-11e2-9aa2-cdf8bf5b1646.png)
[1342617019189](https://f.cloud.github.com/assets/2718371/77110/23707f90-6117-11e2-887f-81ad465bfd40.jpg)
[1342617019189-embed](https://f.cloud.github.com/assets/2718371/77120/201fd966-6118-11e2-89a9-404666e9d265.png)

-Why does the re-encoder resize small images into huge ones? Some of them are so expanded that they look horrible. Is this a bug or an optimization feature?

Feature request (When you have time):
1.Have the program automatically move re-encoded images into a new folder and take out "-embed" from the name.
2.Support for images with unicode names (Japanese)

Hope this helps. I'm running .gif files right now. If I notice anything else, I'll update this.

Again, thanks for working on this. It's awesome.

**Comment by dnsev** [comment]
Perhaps you're missing how this encoder is supposed to work. While the Madotsuki image seems to have some issues, everything else you've described is desired behavior. This re-encodes it using a different format which potentially (almost always) requires the original image to be modified.

Use http://cornarx.6te.net/mask.html if you wish to maintain image format/quality, albeit not a batch application.

The goal of this is basically a final solution, such that it's not easily detectable. As such, it functions as you've seen.

Actually, as far as Madotsuki goes, I guess the 13:40 song is the culprit. I'm actually impressed the 3,037kb .ogg was able to be embedded into a 2,978kb image. But yeah, sounds that large are hardly suitable for this file type.
