### ISSUE TITLE
QR Overlap

### ISSUE THREAD

**Issue by TriumphForks** [dnsev/4cs#40]
Since the 3.8.0 4chanX update the "Choose files" button overlaps the "Sounds" checkbox in the QR, making it unusable

![issue](https://f.cloud.github.com/assets/5265709/990368/c870c4d2-092d-11e3-8e94-69b6813c06a1.png)

**Comment by dnsev** [comment]
Should be fixed in [4.7.1.2](https://github.com/dnsev/4cs/commit/7db234755d91727799524cb553d50005932ee884)
