### ISSUE TITLE
Media Player won't embed Youtube videos on frontpage with newest Appchan X

### ISSUE THREAD

**Issue by SamuraiCaveman** [dnsev/4cs#47]
Since the Appchan X 2.6.4 update (and also in 2.7), the 4chan Media Player has stopped embedding YT links on the frontpage. Inside of threads everything is still fine.

![4535](https://f.cloud.github.com/assets/4655851/1767679/d24cda12-6757-11e3-8418-2d691a781b7f.png)

Firefox 26.0
Greasemonkey 1.13
Appchan 2.7.0 (the issue was also in 2.6.4)

(I didn't know whether to post this here or on the Appchan issues page so I posted it on both)

**Comment by zixaphir** [comment]
I'm fairly certain this is an issue with 4chan X's new-ish Index features. @MayhemYDG hasn't really documented either yet, but two events were added with this feature to monitor and respond to Index changes. They are 'IndexBuild', which contains all added nodes as part of it's event.detail, and 'IndexRefresh', which does not.

Or one could completely circumvent 4chan X's API and just reparse the page with mutationObserver.

**Comment by dnsev** [comment]
Fixed in [5.0](https://github.com/dnsev/4cs/commit/9ad133dbfc93de67b5c1a24f2223caa3e2b8ad85)/[cl](http://dnsev.github.io/4cs/#changes?highlight=5_0&scroll=5_0)
