### ISSUE TITLE
Sounds masked with http://cornarx.6te.net/mask.html won't play

### ISSUE THREAD

**Issue by Lyrica-Prismriver** [dnsev/4cs#5]
I just switched from https://userscripts.org/scripts/show/154526 to your script, but now none of the masked files will play.  I click them, and it loads, but the script's "window" won't display the image and nothing will play.  Old files using older masks play correctly (such as the images in http://archive.foolz.us/a/thread/77601296/), as do images using stego, but new masks won't (such as most of those in https://archive.foolz.us/a/thread/78653026/).

For example, http://www.pictureshack.us/images/84179_440_-_La_Pucelle_-_sm7862914.jpg does not work (new mask), whereas http://www.pictureshack.us/images/64902_Stego.png does (stego).

You've updated your script recently, so I find it hard to believe that your script does not support the only working mask, but I installed the script and made no changes to it, so I don't think I'm doing anything wrong either.

This is really confusing...  Does this really not support the most recent mask?

I'm using Chromium 25.0.1323.1 (Developer Build 167142) Ubuntu 12.10.

**Comment by writen-unclear** [comment]
The problem seems to have been caused by the last update where string_to_uint8array(magic_strings[3]) was supposed to have been removed from var magic_strings_ui8 along with the removal of that entry from magic_strings.  The change was made in web/4cs.dev.user.js but not in web/4cs.full.user.js or web/4cs.user.js.

**Comment by writen-unclear** [comment]
BTW there is no "new mask" at present.  The only change that has been made to the format produced by the masker are that it now pads the images with fake endings such as "\0\0\0\0IEND\xAE\x42\x60\x82", which will result in garbage being appended to the end of the last Ogg file in scripts that don't strip it out, but won't affect playback.

**Comment by dnsev** [comment]
Oh, apparently I forgot to generate the single file scripts when I last updated, and written-unclear seems to be more on the ball than I am about this.

Regardless, I updated it and <i>actually tested</i> the built version on the image this time and it seems to work.
