### ISSUE TITLE
Settings Gone?

### ISSUE THREAD

**Issue by fernadamartz** [dnsev/4cs#51]
The settings for the media player that should be in the 4chanX drop down menu has vanished. Like this:
![things](https://f.cloud.github.com/assets/6591698/2084453/074ecd1e-8e23-11e3-963e-feb290ad9be0.png)

I'm using the latest version of the player (5.0.0.2) and 4chanX (3.16.2), and the browser I'm using is chrome.

**Comment by dnsev** [comment]
Okay so apparently Chrome is (once again) a piece of shit which messes up certain `CustomEvent`s, so the menu isn't being added in Chrome.

Should be updated in [5.0.1](https://github.com/dnsev/4cs/commit/bceb8a9178e013a25da3c2fa72ad0b675f9af696)/[cl](http://dnsev.github.io/4cs/#changes?highlight=5_0_1&scroll=5_0_1) to have the link [here](https://f.cloud.github.com/assets/3087287/2091455/a63b876a-8e9f-11e3-91bf-cef9a9d95a0f.png)
