### ISSUE TITLE
Customizing text in link next to image attributes

### ISSUE THREAD

**Issue by usernamestring** [dnsev/4cs#54]
I would like to customize the 'sounds' link placed next to the image attributes. Is it possible to add support for this, kinda like ExLinks does?
If not, then at least I would like to know if there's an easy way I can customize the 'sounds' link by editing the source script, perhaps by replacing a specific occurrence of this word within the code with the one I want?

**Comment by dnsev** [comment]
Added in [5.0.4](https://github.com/dnsev/4cs/commit/de511ebbdfc6f054122dd76889a9c76fb4169b1f).

Check under the "Styling" section in the settings.
