### ISSUE TITLE
Update for new filesize limits

### ISSUE THREAD

**Issue by Grumblesmorf** [dnsev/4cs#63]
.pngs can be up to 4mb now which would allow for some higher quality outputs with embed.exe. There is probably already a way to set this that I'm just not aware of, but the simple drag 'n drop method will keep trying until it gets the file below 3mb or decides that it isn't possible.

**Comment by dnsev** [comment]
Redownload any .exe files you need, [the default should be updated to 4MB](https://github.com/dnsev/4cs/commit/38474c3919fe5649d7da5c6052b5194a079d227e).
