### ISSUE TITLE
forced readme before install

### ISSUE THREAD

**Issue by Elemarkef** [dnsev/4cs#66]
We get it. you don't like getting asked stupid questions over and over again or having to play nursemaid

But if you are having to reinstall your addons from a new OS install there is nothing more aggrivating than this painfully slow, unskippable event. I've been using this extension forever, but please, please, allow returning users to skip this bullshit.

**Comment by dnsev** [comment]
https://raw.githubusercontent.com/dnsev/4cs/master/web/4cs.user.js

Or also, don't use it. Sounds don't really work anymore and the script is in shambles.

4cs is basically obsolete now, and anything useful in it is in the process of being moved to a separate extension.

**Comment by Elemarkef** [comment]
Fair enough, but I liked having a player for youtube that wasn't a rough embed option that that I could move around and still scroll through the thread while watching the youtube video, even though sounds threads on 4chan are dead

What extension is taking over now?

**Comment by dnsev** [comment]
It's unreleased, but the link previewing feature from 4cs is being moved to a different script. Some sort of embedding which stays on the screen while scrolling is planned too.
