### ISSUE TITLE
Ajax Error

### ISSUE THREAD

**Issue by grenalie** [dnsev/4cs#7]
Keep getting Ajax Error, I'm on Firefox 18.0.1.

**Comment by dnsev** [comment]
If you're in the foolz archive, some images will do this due to them referring back to 4chan, and 4chan tries to prevent leeching from outside sites.

If you aren't, what userscript manager are you using? (Greasemonkey or Scriptish)
And is this occurring on every single image, or only a select few?

**Comment by grenalie** [comment]
It happens on the main site and for every image, I'm using Greasemonkey.

**Comment by dnsev** [comment]
That's strange; I just tested on FF 18.0 and I'm not sure how I can replicate it. Do you have any other userscripts/plugins which may be affecting it?

Alternatively, if you open the dev console (ctrl+shift+K) and check and see if there's anything important in there, that might be good:
![web_console](https://f.cloud.github.com/assets/3087287/120665/f5ae19a6-6d1d-11e2-908c-3a20c28bdb48.png)

Also, maybe clicking+dragging the image into the player works? Give that a shot too; no promises though.

**Comment by dnsev** [comment]
Worth mentioning, even if not directly at this user, and albeit rather late: clicking on the "ajax error" text that appears on broken links opens a message with (hopefully) some info about what went wrong.
