### ISSUE TITLE
Overlap in function with Youtube Link Title

### ISSUE THREAD

**Issue by evilagram** [dnsev/4cs#8]
I'd like to have an option to disable the youtube functionality of this extension, as I prefer youtube link title, and don't want both going off on me on the same page. Could this be added?
http://userscripts.org/scripts/show/83584
This is youtube link title, in case it is important.

**Comment by dnsev** [comment]
You can either disable the other script or turn it off in the settings in this script:
[ Media Player ] -> Settings -> Link Replacement -> Disable the first option

**Comment by dnsev** [comment]
I've also added settings to disable <b>only</b> the video link replacement part; that is, the links are still linkified.

I tested the script you pointed out and it doesn't seem to do it's own linkification, so I let that remain enabled (in case for some reason you didn't want another linkifying script.)
