### ISSUE TITLE
Youtube conflicts with appchanx

### ISSUE THREAD

**Issue by Yoposoc** [dnsev/4cs#9]
Appchan X loads youtube videos inline with the thread, which I personally like better than the 4chan media player's youtube handling. It's probably a personal opinion. Is there a way to disable this? Right now, Appchan X's youtube feature doesn't work since 4chan media player works first.

I'm guessing it's the same with soundcloud. I really like it to be inline with the thread.

**Comment by dnsev** [comment]
If you want to retain replaced links:
[Media Player] -> Settings -> Media URL Replacement -> Disable

If your extension already replaces links:
[Media Player] -> Settings -> URL Replacing -> Disable

**Comment by Yoposoc** [comment]
All I see when I go to settings is this.
http://puu.sh/24iWq
I'm a bit confused. I'm thinking my settings window is supposed to have more....
Edit: I also don't have a question mark button. I already tried reinstalling.

**Comment by dnsev** [comment]
Oh, I should clarify that there are 2 places for settings; that is for the player settings. There should be a link at the top right of the page near the navigation links that says [Media Player], and there also might be one at the bottom.

If you can't see them, disable appchan temporarily and it should appear; I didn't realize it didn't appear when using appchan. I'll see if I can make it appear there or not as well.

**Comment by dnsev** [comment]
In 2.1.5, the [Media Player] link now appears in the nav when using appchan x.
